services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
  redis:
    image: redis:7.0-alpine
    container_name: redis
    env_file:
      - .env.docker
    command: redis-server --save 60 1 --requirepass $REDIS_PASSWORD
    volumes:
      - .docker/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-tier
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - app-tier
    restart: always
networks:
  app-tier:
    driver: bridge